name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World Step
        run:
          echo "Hello, world!"

      - name: Date Step
        run:
          date

      - name: List Files Step
        run:
          ls -l
