name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    name: Simple deployment pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

  tag_release:
    name: Bump version and push tag
    runs-on: ubuntu-latest
    needs: [ simple_deployment_pipeline ]
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip tag]' ) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Update version number
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  deploy_to_render:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [ simple_deployment_pipeline, tag_release ]
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip tag]' ) }}

    steps:
      - name: Deploy to Render
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  discord_notify:
    name: Discord notify
    runs-on: ubuntu-latest
    needs: [ simple_deployment_pipeline, tag_release, deploy_to_render ]
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip tag]' ) }}

    steps:
      - name: Build Success
        uses: rjstone/discord-webhook-notify@v2
        if: success()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          details: All tests passed! Build Successful!

      - name: Build Failed
        uses: rjstone/discord-webhook-notify@v2
        if: failure()
        with:
          avatarUrl: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          details: Failure!
